skip_branch_with_pr: true
version: 1.0.{build}-{branch}
image: Visual Studio 2015
install:
  - nuget restore
configuration: Debug
before_build:
  - git config --global user.name "John Doe"
  - git config --global user.email johndoe@example.com
build:
  verbosity: normal
after_build:
  - mkdir release
  - copy Cement.Net\bin\Debug\cm.exe release\cm.exe
  - copy Cement.Net\bin\Debug\cm.exe.config release\cm.exe.config
  - xcopy files-common release /s /i /Y
  - 7z a release.zip release
artifacts:
  - path: release.zip
deploy:
  provider: GitHub
  description: automatic release
  artifact: release.zip
  auth_token:
    secure: 4ZYJdojxUj1R94fuci26zjd+Rs1Hmy5lPmPKi+/FWMwSJFTccFzgpsm3uHP/y4i8
  on:
    branch: master
    appveyor_repo_tag: true